plugins { id 'com.android.application' }

android {
    namespace 'za.co.victoriatuition.vcloud'
    compileSdk 35

    defaultConfig {
        applicationId "za.co.victoriatuition.vcloud"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
    }
}

dependencies {}
